version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - composer
      - database

  composer:
    image: composer:2
    container_name: symfony_composer
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["composer"]

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: